sudo: required
dist: bionic

# disable travis builds everywhere, because macos builds are paid now
branches:
  only:
    - travis

os:
  - linux
  - osx

osx_image: xcode9.4

services:
  - docker

env:
  global:
    - secure: yVhN4PaIpLMKJdUGckSghbC6biQjZrKiVulcA/xloFHgCe/MJgdpqlZmIuruKPEi95sf6yC7Trcg9NlPgIDJwAlQxBggMdsSG50Kkej/JG1sW59BDm51x6ajHgWLDDAQXW4z5OflCx3o87j7apXHP0bk6RcIrisgms6ndN5I8T0T2lTy3MBwQgTa1MsP36dpPHLygCoHSTzS877jK8dKKV270P1QivuDoWNYoypE3FTVMs8hxOFklw1EnRgD9GIDe6msIwA0NOZkZa2qhC7AL5zrqiAOrFj5fE4I7B2q0YwQ4S308pXRIqfPKIciMrZh/jNYG9GxHVPuH0f4coE9Xyde/sUauQXEW625jcARAPXkqIWTxcSB9J+gOuScDQzFIIHlJ/MqS2Cp1podoBvhrcuFS8blXy2ay7BTPFb5Ju2jkxcHQ3BfN/ZFV1O10HVpsvgk+cucwfjTSvkqyaKgrHAX/lWtzsJ6OuBb5NhAsko6/v+JKi5f0IsbT4d2MI6Xf7mjfIJQlrslCShWTtPKYfy/WjCOfh0tbx53ScAL6F0Q8Hv9wtOHxTKXssEskVyVNrqY5wiFaOiImfL/NTWiPwPz4rSlu4dssZHZuyKRi5PlTHy1lqEkWvJx4v9uc2abHethJsCqtPnbfw8GTnr/8vhKuVjWfVuQgihw6Y8pcqk=
    - secure: SFqSIIcMJFiQVaRaHYwfmDNuchJjSN5gzAycFODAVL42H1MIGJ0LOkfs3GazWlopLENqeTP0Q0Ai5xN8gpxxbLNpyAJtAxd628cHKaiyd+oeCh9nStOiOT7YhfSK++uqIFlr6Eya3yzzPvCoJEWc2CpHrZDV49nrEbeWRH57jMtQtmnn3qXz4GMPptkyPBrE7VGaNx9eFH4glvM7cNdN02aiZZMdJFk6OfJMlaymh1IQwXHSmxEXG5k3GZbxPgAvOT7KqDBxQbUg6y9VXviB48d1obpIJsPS+RmDyCD2F0gcdLVHTNCgIWd+EBXa0H6za/LEdGH3xO8COLumjGxOtbo05MPn45FvczEbQrkuoz46ZA7DkUJsinzNNkiwFKI82RmWXPjmNfItCgd2VMnWfYuMl/Q4hL48GG4s6t+TtvuhtNfoBKANHtnRM3z4wA0N0KMR1WWIhoDOcLkzhy8Fir3JE1hX7WrbUgltC8Vk93beTWnNg8BmALZjeplzvCN4sKdLVEtTD2N6P+w97EOPTPywq1lITyqe51JriC70MpI4SuHklZc/lvfsGaREtJ4FLJ5miJxtKaIyKKccZxNMKf0E2SDJyVopYldvE1+USsPk3ZrD5SEUHZtfQM0UCNuJ+Kwn7uBcQkGnlBlK6/EMIdWifATBQUsLR3YjoBlZZzM=

language: java

addons:
  apt:
    packages:
      - maven
      - python3
      - python3-setuptools
      - python3-pip
      - python-pygments
      # - r-base
      - libxml2-dev
      - valgrind
  # R disabled. It's taking up too much time in CI
  # homebrew:
  #   packages:
  #     - r
  #   update: true

install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install cmake==3.13.3
  - sudo -H pip3 install --upgrade setuptools wheel virtualenv
  - sudo -H pip3 install $TRAVIS_BUILD_DIR/emulator
  - sudo -H pip3 install awscli
  # R disabled. It's taking up too much time in CI
  # # install required packages for R
  # - sudo -H R --vanilla -e 'install.packages("knitr", repos="http://cran.us.r-project.org")'
  # - sudo -H R --vanilla -e 'install.packages("reticulate", repos="http://cran.us.r-project.org")'

before_script:
  # need to build in manylinux docker container!
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker pull dockcross/manylinux2014-x64 ;
    fi
    # for all tests except C++ we need libraries built inside docker and we need them for production
    # for C++ test we need libs to be compiled in the same env as test
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cd $TRAVIS_BUILD_DIR && mkdir build_outside && cd build_outside && cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed -DCMAKE_BUILD_TYPE=Release .. && sudo -H make && make install;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker run -e TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR dockcross/manylinux2014-x64 /bin/bash -c "/opt/python/cp36-cp36m/bin/pip3.6 install cmake==3.13.3 && cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed_docker -DCMAKE_BUILD_TYPE=Release .. && make && make install" ;
    fi
  # build for mac
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed -DCMAKE_BUILD_TYPE=Release .. && make -j && make install ;
    fi
  - sudo -H pip3 install $TRAVIS_BUILD_DIR/python-package
  - sudo -H pip3 install -r $TRAVIS_BUILD_DIR/tests/python/requirements.txt
  # R disabled. It's taking up too much time in CI
  # - cd $TRAVIS_BUILD_DIR/r-package/brainflow && sudo -H R CMD build . && sudo -H R CMD INSTALL brainflow_0.0.0.9000.tar.gz
  - cd $TRAVIS_BUILD_DIR/tests/cpp/get_data_demo && mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/installed .. && make -j
  - cd $TRAVIS_BUILD_DIR/tests/cpp/signal_processing_demo && mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/installed .. && make -j
  - cd $TRAVIS_BUILD_DIR/tests/cpp/ml_demo && mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/installed .. && make -j
  - cd $TRAVIS_BUILD_DIR && cd java-package/brainflow && mvn package
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cp $TRAVIS_BUILD_DIR/java-package/brainflow/target/classes/brainflow/*.so $TRAVIS_BUILD_DIR/java-package/brainflow/target/classes/ ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cp $TRAVIS_BUILD_DIR/java-package/brainflow/target/classes/brainflow/*.dylib $TRAVIS_BUILD_DIR/java-package/brainflow/target/classes/ ;
    fi

after_success:
  # push libraries from docker!
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      aws s3 cp $TRAVIS_BUILD_DIR/installed_docker/lib/ s3://brainflow/$TRAVIS_COMMIT/$TRAVIS_OS_NAME --recursive ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      aws s3 cp $TRAVIS_BUILD_DIR/installed/lib/ s3://brainflow/$TRAVIS_COMMIT/$TRAVIS_OS_NAME --recursive ;
    fi
  # push results of static analyzer
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      aws s3 cp $TRAVIS_BUILD_DIR/report s3://brainflow-artifacts/$TRAVIS_COMMIT/report --recursive ;
    fi
   # notify that everything is ok
  - echo success > ${TRAVIS_OS_NAME}_success && aws s3 cp ${TRAVIS_OS_NAME}_success s3://brainflow/$TRAVIS_COMMIT/

after_failure:
  # notify Appveyor of travis test failure
  echo failure > ${TRAVIS_OS_NAME}_failure && aws s3 cp ${TRAVIS_OS_NAME}_failure s3://brainflow/$TRAVIS_COMMIT/

notifications:
  email:
    on_success: never
    on_failure: always
