[brainflow]
git-tree-sha1 = "c117cdffbecd63015eab35a8979a1373778e6e34"
lazy = true

    [[brainflow.download]]
    sha256 = "cda3acf5b5cfa30e2860cd8c1f4f1fa43a7df051d383c973c0579227527bb23a"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/3.9.0/compiled_libs.tar"
