[brainflow]
git-tree-sha1 = "a8a4372188aefa0038ee785f564eafebdd907f40"
lazy = true

    [[brainflow.download]]
    sha256 = "77d3c534587320a6bf565b11a52e775b1aaf485e877e0a77d5317cdebadc83fb"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.2.1/compiled_libs.tar"
