name: CppCheck

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    # need newer version than available from apt-get
    - name: Install CppCheck
      run: |
        git clone https://github.com/danmar/cppcheck
        cd cppcheck
        git checkout 2.3
        mkdir build
        cd build
        cmake ..
        make -j
        sudo -H make install
    - name: Run Cppcheck
      run: cppcheck --std=c++11 --error-exitcode=1 --xml --xml-version=2 --force src cpp-package third_party 2>cppcheck_res.xml
    - name: Generate Report
      if: ${{ failure() }}
      run: cppcheck-htmlreport --title=BrainFlow --file=cppcheck_res.xml --report-dir=report
    - name: Upload Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: report
