name: Run Deploy

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: 1.0.0
        required: true

jobs:
  RunDeploy:
    runs-on: windows-2019

    steps:
    # Install Dependencies
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Install Python Deploy Tools
      run: |
        python -m pip install wheel
        python -m pip install twine
        python -m pip install awscli
      shell: cmd
    # GITHUB_REF variable has some garbage before tag name
    - name: Get Version
      id: get_version
      run: |
        $SOURCE_TAG = ${env:GITHUB_REF} -replace "refs/tags/", ""
        If ($SOURCE_TAG -eq "" -or $SOURCE_TAG -eq $null) {
          $SOURCE_TAG = ${{ github.event.inputs.version }}
        }
        echo "::set-output name=SOURCE_TAG::$SOURCE_TAG"
        echo SOURCE_TAG=$SOURCE_TAG>>${env:GITHUB_ENV}
    # Download all artifacts from AWS
    - name: Download Linux Libs
      run: |
        New-Item $env:GITHUB_WORKSPACE\linux -itemtype directory
        aws s3 cp s3://brainflow/$env:GITHUB_SHA/linux/ $env:GITHUB_WORKSPACE\linux\ --recursive
        ls $env:GITHUB_WORKSPACE\linux\
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Download MacOS Libs
      run: |
        New-Item $env:GITHUB_WORKSPACE\macos -itemtype directory
        aws s3 cp s3://brainflow/$env:GITHUB_SHA/macos_release/ $env:GITHUB_WORKSPACE\macos\ --recursive
        ls $env:GITHUB_WORKSPACE\macos\
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Download Win x64 Libs
      run: |
        New-Item $env:GITHUB_WORKSPACE\win64 -itemtype directory
        aws s3 cp s3://brainflow/$env:GITHUB_SHA/win64/lib/ $env:GITHUB_WORKSPACE\win64\ --recursive
        ls $env:GITHUB_WORKSPACE\win64\
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Download Win x32 Libs
      run: |
        New-Item $env:GITHUB_WORKSPACE\win32 -itemtype directory
        aws s3 cp s3://brainflow/$env:GITHUB_SHA/win32/lib/ $env:GITHUB_WORKSPACE\win32\ --recursive
        ls $env:GITHUB_WORKSPACE\win32\
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Publish packages
    - name: Publish Java Package
      run: |
        cd $env:GITHUB_WORKSPACE\java-package\brainflow
        Copy-Item "$env:GITHUB_WORKSPACE\linux\*" -Destination "$env:GITHUB_WORKSPACE\java-package\brainflow\src\main\resources" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\osx\*" -Destination "$env:GITHUB_WORKSPACE\java-package\brainflow\src\main\resources" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\win64\*" -Destination "$env:GITHUB_WORKSPACE\java-package\brainflow\src\main\resources" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\win32\*" -Destination "$env:GITHUB_WORKSPACE\java-package\brainflow\src\main\resources" -Recurse
        ls $env:GITHUB_WORKSPACE\java-package\brainflow\src\main\resources
        (gc .\pom.xml).replace('0.0.1-SNAPSHOT',$env:SOURCE_TAG) | Out-File -encoding ASCII pom.xml
        (gc .\settings.xml).replace('USER',$env:PUBLISH_USER) | Out-File -encoding ASCII settings.xml
        (gc .\settings.xml).replace('TOKEN',$env:PUBLISH_TOKEN) | Out-File -encoding ASCII settings.xml
        mvn package
        #mvn -s $env:GITHUB_WORKSPACE\java-package\brainflow\settings.xml deploy -Dregistry=https://maven.pkg.github.com/brainflow-dev -Dtoken=$env:PUBLISH_TOKEN
        aws s3 cp $env:GITHUB_WORKSPACE\java-package\brainflow\target\ s3://brainflow/$env:GITHUB_SHA/jars --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
    - name: Publish Python Package
      run: |
        cd $env:GITHUB_WORKSPACE\python-package\brainflow\
        Copy-Item "$env:GITHUB_WORKSPACE\linux\*" -Destination "$env:GITHUB_WORKSPACE\python-package\brainflow\lib" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\osx\*" -Destination "$env:GITHUB_WORKSPACE\python-package\brainflow\lib" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\win64\*" -Destination "$env:GITHUB_WORKSPACE\python-package\brainflow\lib" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\win32\*" -Destination "$env:GITHUB_WORKSPACE\python-package\brainflow\lib" -Recurse
        ls $env:GITHUB_WORKSPACE\python-package\brainflow\lib
        (gc .\setup.py).replace('0.0.1',$env:SOURCE_TAG) | Out-File -encoding ASCII setup.py
        python setup.py sdist bdist_wheel
        #twine upload --skip-existing dist/*.whl --user Andrey1994 --password $env:PYPI_PASSWORD
        aws s3 cp $env:GITHUB_WORKSPACE\python-package\brainflow\ s3://brainflow/$env:GITHUB_SHA/whl --recursive
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Publish Nuget Package
      run: |
        cd $env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow
        (gc .\brainflow.nuspec).replace('0.0.1',$env:SOURCE_TAG) | Out-File -encoding ASCII brainflow.nuspec
        Copy-Item "$env:GITHUB_WORKSPACE\linux\*" -Destination "$env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow\lib" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\osx\*" -Destination "$env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow\lib" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\win64\*" -Destination "$env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow\lib" -Recurse
        Copy-Item "$env:GITHUB_WORKSPACE\win32\*" -Destination "$env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow\lib" -Recurse
        ls $env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow\lib
        nuget pack brainflow.csproj -properties Configuration=Release -IncludeReferencedProjects
        aws s3 cp $env:GITHUB_WORKSPACE\csharp-package\brainflow\brainflow s3://brainflow/$env:GITHUB_SHA/nuget --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
