name: Deploy Cpp libs

on: [push]

jobs:
  CppWindows:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        msvc_runtime: [static, dynamic]
        build_type: [Release, Debug]
        arch: [Win32, x64, ARM, ARM64]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    # compile and prepare everything
    - name: Compile ${{ matrix.build_type }} ${{ matrix.arch }} with MSVC runtime ${{ matrix.msvc_runtime }}
      run: |
        mkdir %GITHUB_WORKSPACE%\%BUILD%_%RUNTIME%_%ARCH%
        cd %GITHUB_WORKSPACE%\%BUILD%_%RUNTIME%_%ARCH%
        cmake -G "Visual Studio 16 2019" -A %ARCH% -DCMAKE_SYSTEM_VERSION=8.1 -DMSVC_RUNTIME=%RUNTIME% -DCMAKE_INSTALL_PREFIX=..\artifacts\%BUILD%_%RUNTIME%_%ARCH%\ ..
        cmake --build . --target install --config %BUILD% -j 2 --parallel 2
      shell: cmd
      env:
        RUNTIME: ${{ matrix.msvc_runtime }}
        BUILD: ${{ matrix.build_type }}
        ARCH: ${{ matrix.arch }}

    # Start Deploy Stage
    - name: Upload Report ${{ matrix.build_type }} ${{ matrix.arch }} with MSVC runtime ${{ matrix.msvc_runtime }}
      uses: actions/upload-artifact@v1
      with:
        name: windows_${{ matrix.build_type }}_${{ matrix.arch }}_${{ matrix.msvc_runtime }}
        path: artifacts
    - name: Install Python AWS Tools
      run: |
        python -m pip install awscli
      shell: cmd
    - name: Upload Libs to AWS
      if: ${{ github.event_name == 'push' && github.repository == 'brainflow-dev/brainflow' }}
      run: |
        aws s3 cp %GITHUB_WORKSPACE%\artifacts\%BUILD%_%RUNTIME%_%ARCH%\ s3://brainflow/%GITHUB_SHA%/artifacts/%BUILD%_%RUNTIME%_%ARCH% --recursive
      shell: cmd
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        RUNTIME: ${{ matrix.msvc_runtime }}
        BUILD: ${{ matrix.build_type }}
        ARCH: ${{ matrix.arch }}
