name: Deploy Cpp libs

on: [push]

jobs:
  CppWindows:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        msvc_runtime: [static, dynamic]
        build_type: [Release, Debug]
        arch: [Win32, x64]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    # compile and prepare everything
    - name: Compile ${{ matrix.build_type }} ${{ matrix.arch }} with MSVC runtime ${{ matrix.msvc_runtime }}
      run: |
        mkdir %GITHUB_WORKSPACE%\%BUILD%_%RUNTIME%_%ARCH%
        cd %GITHUB_WORKSPACE%\%BUILD%_%RUNTIME%_%ARCH%
        cmake -DWARNINGS_AS_ERRORS=ON -G "Visual Studio 16 2019" -A %ARCH% -DCMAKE_SYSTEM_VERSION=8.1 -DMSVC_RUNTIME=%RUNTIME% -DCMAKE_INSTALL_PREFIX=..\artifacts\%BUILD%_%RUNTIME%_%ARCH%\ ..
        cmake --build . --target install --config %BUILD% -j 2 --parallel 2
      shell: cmd
      env:
        RUNTIME: ${{ matrix.msvc_runtime }}
        BUILD: ${{ matrix.build_type }}
        ARCH: ${{ matrix.arch }}

    # Start Deploy Stage
    - name: Upload Report ${{ matrix.build_type }} ${{ matrix.arch }} with MSVC runtime ${{ matrix.msvc_runtime }}
      uses: actions/upload-artifact@v1
      with:
        name: windows_${{ matrix.build_type }}_${{ matrix.arch }}_${{ matrix.msvc_runtime }}
        path: artifacts
    - name: Install Python AWS Tools
      run: |
        python -m pip install awscli
      shell: cmd
    - name: Upload Libs to AWS
      if: ${{ github.repository == 'brainflow-dev/brainflow' }}
      run: |
        aws s3 cp %GITHUB_WORKSPACE%\artifacts\%BUILD%_%RUNTIME%_%ARCH%\ s3://brainflow/%GITHUB_SHA%/artifacts/%BUILD%_%RUNTIME%_%ARCH% --recursive
      shell: cmd
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        RUNTIME: ${{ matrix.msvc_runtime }}
        BUILD: ${{ matrix.build_type }}
        ARCH: ${{ matrix.arch }}

  CppUnix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        build_type: [Release, Debug]
        os: [ubuntu-18.04, macos-10.15]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Install Python Dependencies
      if: (matrix.os == 'ubuntu-18.04')
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y python3-setuptools python3-pygments
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    # compile for macos and linux
    - name: Compile BrainFlow for MacOS
      if: (matrix.os == 'macos-10.15')
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DWARNINGS_AS_ERRORS=ON -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/artifacts/macos_$BUILD -DCMAKE_BUILD_TYPE=$BUILD ..
        make -j
        make install
      env:
        BUILD: ${{ matrix.build_type }}
    - name: Compile BrainFlow in ManyLinux
      if: (matrix.os == 'ubuntu-18.04')
      run: |
        docker pull dockcross/manylinux2014-x64
        docker run -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE -e BUILD=$BUILD -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE dockcross/manylinux2014-x64 /bin/bash -c "/opt/python/cp36-cp36m/bin/pip3.6 install cmake==3.13.3 && cd $GITHUB_WORKSPACE && mkdir build_docker && cd build_docker && cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/artifacts/linux_${BUILD} -DCMAKE_BUILD_TYPE=$BUILD .. && make -j && make install"
      env:
        BUILD: ${{ matrix.build_type }}
    # start deploy stage
    - name: Install Python AWS Tools
      run: |
        sudo -H python -m pip install awscli
      shell: cmd
    - name: Upload MacOS Libs to AWS
      if: ${{ matrix.os == 'macos-10.15' && github.repository == 'brainflow-dev/brainflow' }}
      run: |
        aws s3 cp $GITHUB_WORKSPACE/artifacts/macos_$BUILD s3://brainflow/$GITHUB_SHA/artifacts/macos_$BUILD --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUILD: ${{ matrix.build_type }}
    - name: Upload Linux Libs to AWS
      if: ${{ matrix.os == 'ubuntu-18.04' && github.repository == 'brainflow-dev/brainflow' }}
      run: |
        aws s3 cp $GITHUB_WORKSPACE/artifacts/linux_$BUILD s3://brainflow/$GITHUB_SHA/artifacts/linux_$BUILD --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUILD: ${{ matrix.build_type }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}_${{ matrix.build_type }}
        path: artifacts
