name: Run MacOS Self-Hosted

# run it only to build release
# there is old MacOS version to target more devices than we can do using github actions image
# on: [push, pull_request]
on:
  push:
    tags: 
      - '*'

jobs:
  RunSelfHosted:
    runs-on: self-hosted

    steps:
    # compile and prepare env
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Compile BrainFlow
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Release ..
        make -j
        make install

    # deploy started
    - name: Install AWS CLI
      run: sudo -H python -m pip install awscli
    - name: Push Libraries MacOS Dev
      if: (matrix.os == 'macos-latest')
      run: |
        aws s3 cp $GITHUB_WORKSPACE/installed/lib/ s3://brainflow/$GITHUB_SHA/macos_release --recursive
        echo success > macos_release_success
        aws s3 cp macos_release_success s3://brainflow/$GITHUB_SHA/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}