name: Run Windows

on: [push, pull_request]

jobs:
  RunWindows:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [windows-2019]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Set Path
      run: |
        echo %GITHUB_WORKSPACE%\tools>>%GITHUB_PATH%
        echo %GITHUB_WORKSPACE%\installed32\lib>>%GITHUB_PATH%
        echo %GITHUB_WORKSPACE%\installed32\lib>>%GITHUB_PATH%
      shell: cmd
    # compile and prepare everything
    - name: Compile x32
      run: |
        mkdir %GITHUB_WORKSPACE%\build32
        cd %GITHUB_WORKSPACE%\build32
        cmake -G "Visual Studio 16 2019"-A x86 -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_INSTALL_PREFIX=..\installed32\ ..
        cmake --build . --target install --config Release -j 2 --parallel 2
      shell: cmd
    - name: Compile x64
      run: |
        mkdir %GITHUB_WORKSPACE%\build64
        cd %GITHUB_WORKSPACE%\build64
        cmake -G "Visual Studio 16 2019"-A x64 -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_INSTALL_PREFIX=..\installed64\ ..
        cmake --build . --target install --config Release -j 2 --parallel 2
      shell: cmd
    - name: Nuget
      run: |
        nuget install Accord -OutputDirectory %GITHUB_WORKSPACE%\csharp-package\brainflow\packages
        nuget install Accord.Math -OutputDirectory %GITHUB_WORKSPACE%\csharp-package\brainflow\packages
      shell: cmd
    - name: C# build
      run: |
        cd %GITHUB_WORKSPACE%\csharp-package\brainflow
        msbuild brainflow.sln /p:Configuration=Release /p:Platform="Any CPU"
    - name: Install Emulator
      run: |
        pip install %APPVEYOR_BUILD_FOLDER%\emulator\
        cd %GITHUB_WORKSPACE%
        .\emulator\brainflow_emulator\com0com\certmgr.exe  /add %GITHUB_WORKSPACE%\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine root
        .\emulator\brainflow_emulator\com0com\certmgr.exe /add %GITHUB_WORKSPACE%\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine trustedpublisher
    - name: Install Python package
      run: |
        pip install %GITHUB_WORKSPACE%\python-package\
        pip install -r %GITHUB_WORKSPACE%\tests\python\requirements.txt