name: Run Windows

on: [push, pull_request]

jobs:
  RunWindows:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [windows-2019]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    # compile Android Libs for all ABIs
    - name: Compile Android arm64-v8a
      run: |
        set PATH=%GITHUB_WORKSPACE%\tools;%PATH%
        mkdir %GITHUB_WORKSPACE%\build_armv8
        cd %GITHUB_WORKSPACE%\build_armv8
        cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=android-19 -DANDROID_ABI=arm64-v8a ..
        cmake --build . --target install --config Release -j 2 --parallel 2
      shell: cmd

