name: Run Unix

on: [push, pull_request]

jobs:
  RunUnix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    steps:
    # compile and prepare env
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Install Python Dependencies
      if: (matrix.os == 'ubuntu-18.04')
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y python3-setuptools python3-pygments
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.2.0 
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile BrainFlow
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Release ..
        make -j
        make install
    - name: Compile BrainFlow in ManyLinux
      # bindings in production have to use libraries compiled inside this image!
      if: (matrix.os == 'ubuntu-18.04')
      run: |
        docker pull dockcross/manylinux2014-x64
        docker run -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE dockcross/manylinux2014-x64 /bin/bash -c "/opt/python/cp36-cp36m/bin/pip3.6 install cmake==3.13.3 && cd $GITHUB_WORKSPACE && mkdir build_docker && cd build_docker && cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/installed_docker -DCMAKE_BUILD_TYPE=Release .. && make -j && make install"
    - name: Setup Python Package
      run: |
        cd $GITHUB_WORKSPACE/python-package
        sudo -H python3 -m pip install -U .
    - name: Setup Java package
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn package
        cp -av $GITHUB_WORKSPACE/java-package/brainflow/target/classes/brainflow/. $GITHUB_WORKSPACE/java-package/brainflow/target/classes/ 
        cp -av $GITHUB_WORKSPACE/java-package/brainflow/target/classes/brainflow/. $GITHUB_WORKSPACE/java-package/brainflow/target/classes/
    - name: Build Get Data Test
      run: |
        cd $GITHUB_WORKSPACE/tests/cpp/get_data_demo
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/installed ..
        make -j
    - name: Build Signal Processing Test
      run: |
        cd $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/installed ..
        make -j
    - name: Build ML Demo Test
      run: |
        cd $GITHUB_WORKSPACE/tests/cpp/ml_demo
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/installed ..
        make -j
    - name: Install Emulator
      run: |
        cd $GITHUB_WORKSPACE/emulator
        sudo -H python3 -m pip install -U .
    - name: Install Python test Dependencies
      run: sudo -H python3 -m pip install -r $GITHUB_WORKSPACE/tests/python/requirements.txt

    # start testing
    - name: Cyton Python
      run: sudo -H python3 ./emulator/brainflow_emulator/cyton_linux.py python3 $GITHUB_WORKSPACE/tests/python/brainflow_get_data.py --log --board-id 0 --serial-port 
    - name: Multiboard Python
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/cyton_linux.py python3 $GITHUB_WORKSPACE/tests/python/brainflow_multiboard_get_data.py --log --board-id 0 --serial-port
    - name: Cyton Cpp
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/cyton_linux.py $GITHUB_WORKSPACE/tests/cpp/get_data_demo/build/brainflow_get_data --board-id 0 --serial-port
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Synthetic Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/brainflow_get_data.py --log --board-id -1 --streamer-params file://$GITHUB_WORKSPACE/test.csv:w
    - name: Synthetic Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/get_data_demo/build/brainflow_get_data --board-id -1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Synthetic Java
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn exec:java -Dexec.mainClass="brainflow.examples.BrainFlowGetData" -Dexec.args="--board-id -1"
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Cyton Daisy Python
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/cyton_linux.py python3 $GITHUB_WORKSPACE/tests/python/brainflow_get_data.py --log --board-id 2 --serial-port 
    - name: Galea Cpp
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/galea_udp.py $GITHUB_WORKSPACE/tests/cpp/get_data_demo/build/brainflow_get_data --board-id 3 --ip-address 127.0.0.1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Streaming Python
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/streaming_board_emulator.py python3 $GITHUB_WORKSPACE/tests/python/brainflow_get_data.py --log --board-id -2 --ip-address 225.1.1.1 --ip-port 6677 --other-info -1
    - name: Fascia Python
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/fascia_emulator_ci.py python3 $GITHUB_WORKSPACE/tests/python/brainflow_get_data.py --board-id 12 --ip-port 7789
    - name: IronBCI Cpp
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/ironbci_linux.py $GITHUB_WORKSPACE/tests/cpp/get_data_demo/build/brainflow_get_data --board-id 15 --serial-port
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Denoising Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/denoising.py
    - name: Serialization Python
      run: |
        cd $GITHUB_WORKSPACE
        sudo -H python3 $GITHUB_WORKSPACE/tests/python/serialization.py
    - name: Filters Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/signal_filtering.py
    - name: Transforms Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/transforms.py
    - name: Downsampling Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/downsampling.py
    - name: MNE Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/brainflow_to_mne.py
    - name: BandPower Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/band_power.py
    - name: BandPowerAll Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/band_power_all.py
    - name: Denoising Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo/build/denoising
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Downsampling Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo/build/downsampling
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Filters Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo/build/signal_filtering
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Serialization Cpp
      run: |
        cd $GITHUB_WORKSPACE
        sudo -H $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo/build/serialization
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Transforms Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo/build/transforms
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: BandPower Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/signal_processing_demo/build/band_power
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Denoising Java
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn exec:java -Dexec.mainClass="brainflow.examples.Denoising"
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Downsampling Java
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn exec:java -Dexec.mainClass="brainflow.examples.Downsampling"
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Transforms Java
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn exec:java -Dexec.mainClass="brainflow.examples.Transforms"
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: BandPower Java
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn exec:java -Dexec.mainClass="brainflow.examples.BandPower"
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: EEG Metrics Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/eeg_metrics.py --board-id -1
    - name: EEG Metrics Custom Python
      run: sudo -H python3 $GITHUB_WORKSPACE/tests/python/eeg_metrics_ci.py --board-id -1 --classifier 2 --metric 1
    - name: EEG Metrics Cpp
      run: $GITHUB_WORKSPACE/tests/cpp/ml_demo/build/eeg_metrics --board-id -1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: EEG Metrics Java
      run: |
        cd $GITHUB_WORKSPACE/java-package/brainflow
        mvn exec:java -Dexec.mainClass="brainflow.examples.EEGMetrics" -Dexec.args="--board-id -1"
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Run Julia Tests
      run: |
        cd $GITHUB_WORKSPACE/julia-package/brainflow
        julia --project=. -e "import Pkg; Pkg.test()"
      LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    # deploy started
    - name: Install AWS CLI
      run: sudo -H python3 -m pip install awscli
    - name: Push Libraries Linux Docker
      if: (matrix.os == 'ubuntu-18.04') && (${{ github.event_name == 'push' }})
      run: |
        aws s3 cp $GITHUB_WORKSPACE/installed_docker/lib/ s3://brainflow/$GITHUB_SHA/linux --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Push Libraries MacOS Dev
      if: (matrix.os == 'macos-10.15') && (${{ github.event_name == 'push' }})
      run: |
        aws s3 cp $GITHUB_WORKSPACE/installed/lib/ s3://brainflow/$GITHUB_SHA/macos_dev --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


