name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue, need to tale a look'
        stale-pr-message: 'Stale pull request, need to take a look'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
